language: node_js
node_js:
  - stable

script:
  - npm install
  - npm test
  - npm run build

deploy:
  provider: surge
  domain: timerapp.nabeelfarid.surge.sh
  project: ./build/

on:
  branch: master

