language: node_js
node_js:
  - stable

script:
  - npm install
  - npm test
  - npm run build
  - npm install --g surge
  - run: surge ./build https://timerapp.nabeelfarid.surge.sh --token $SURGE_TOKEN

deploy:
  provider: surge
  edge: true
  project: ./build/
  domain: timerapp.nabeelfarid.surge.sh
