language: node_js
node_js:
  - stable

script:
  - npm install
  - npm test
  - npm run build
  - npm install --g surge

deploy:
  provider: surge
  project: ./build/
  skip_cleanup: true
  domain: timerapp.nabeelfarid.surge.sh
